name: Terraform fmt check and auto-format

on:
  push:

jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7
      
      - name: Terraform fmt check
        id: fmt-check
        continue-on-error: true
        run: |
          terraform fmt -check -recursive
          if [ $? -eq 3 ]; then
            echo "fmt_failed=true" >> $GITHUB_OUTPUT
          else
            echo "fmt_failed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run terraform fmt if check failed
        if: steps.fmt-check.outputs.fmt_failed == 'true'
        run: terraform fmt -recursive
      
      - name: Commit changes if files were formatted
        if: steps.fmt-check.outputs.fmt_failed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "chore: terraform fmt"
          git push