name: Terraform fmt check

on:
  push:
    branches:
      - '**'

jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
          
      - name: Terraform fmt
        run: terraform fmt -check -recursive